### ISSUE TITLE
Feature request - Allow manual additions to soft reserve

### ISSUE THREAD

**Issue by Blizz991** [Road-block/BastionEPGP#9]
Been looking at using your addon as a soft reserve system.

Very impressed with how it works so far, and does exactly what I was looking for, with one minor feature missing:

I'd like to allow people to soft reserve ahead of time, without requiring me to be online.
The idea is to simply soft reserve on discord / a google docs - and then instead of having people do it again from ingame, simply allow the group leader to manually add people (while also keeping current functionality of course).

Perhaps something like: 
_/{addonName} res {playerName} {itemLink}_

**What does it solve?**
In the pug world, people are more likely to come to a run if they can see there isn't a bunch of soft reserves on an item they're interested in. 
By requiring them to use the addon, this information is not available prior to the run
(bar leader being online and taking whispers and manually updating it over time on discord, or another place).

**Comment by Road-block** [comment]
I am reluctant to do this for a couple reasons.  
1. When the item is added from an incoming whisper, verifying both the item and the player is trivial. This is the reason you get your nice class colors and all that. ![plusroll-reserves-locked](https://user-images.githubusercontent.com/109839/86737344-e4f42e00-c03c-11ea-8a32-0deaaa0dd86b.png)
Adding a player manually would require iterating your raid members (in which case both them and yourself are online and they can simply whisper you) or sending /who requests (which is a whole other can of worms it being a protected action) or adding a name blindly and hoping you didn't typo it (player names with strange characters for example?)  
2. Players can only change their reserve themselves under the current implementation. ML cannot add and cannot remove, they can only lock and unlock (either the whole list or individual items) and let the player themselves manage their reserve and the whole "transaction" is easily documented in whispers (which can be reviewed in case of a scam report or whatever). This ensures a level of trust. If I let the ML trivially mess with the list they could also easily change someone's reserve from [Razzashi Raptor] to [Alterac Swiss].

Going on a slight tangent the ML doesn't have to manually or item by item update the reserve list to an external place (like a discord channel). It can be exported as a whole when locked (before the raid starts pulling for example. 
![reserves-export](https://user-images.githubusercontent.com/109839/86739219-64cec800-c03e-11ea-83c0-bb0e4af4e309.png)

Anyway, I'm sorry I can't give you a better answer, if you're not using any of the addon's main facilities and only interested in the plusroll / soft-reserve system I could suggest maybe trying out a more full-featured addon that's devoted entirely to that? 

[LootReserve](https://www.curseforge.com/wow/addons/lootreserve) would be an example.

PS. _One thing I will try to add (if I can implement it in a way that doesn't spam addon comms too much) is a way for players to request the full reserve list while reservations are ongoing._

**Comment by Blizz991** [comment]
That's fair, only a thought of course :)

I can see it being a problem getting the bindings setup correctly for the players (I'm assuming you save information when the reserves happen currently), and do see your point with the history from whispers.

I'd think the best approach if a feature was to be implemented (fully aware it's a nope, just for the sake of argument), I'd imagine the leader should be unable to change it, and players would still be able to change / add after the list was created in the first place.

I do see how things can get pretty messy with it though, thanks for the reply either way.

The main reason I ended up with your addon, was that it's the closest I could get to what I was looking for in terms of functionality (and I love the way you handle rolling, nice one!).

Thanks again!
